[cursor.style]
shape = "beam"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
key = "K"
mods = "Control"
action = "Copy"

[scrolling]
multiplier = 10

[terminal]
shell = "fish"
